package org.session.libsession.utilities

// String substitution keys for use with the Phrase library.
// Note: The substitution will be to {app_name} etc. in the strings - but do NOT include the curly braces in these keys!
object StringSubstitutionConstants {
    const val ACCOUNT_ID_KEY                 = "account_id"
    const val APP_NAME_KEY                   = "app_name"
    const val AUTHOR_KEY                     = "author"
    const val COMMUNITY_NAME_KEY             = "community_name"
    const val CONVERSATION_COUNT_KEY         = "conversation_count"
    const val CONVERSATION_NAME_KEY          = "conversation_name"
    const val COUNT_KEY                      = "count"
    const val DATE_KEY                       = "date"
    const val DATE_TIME_KEY                  = "date_time"
    const val DISAPPEARING_MESSAGES_TYPE_KEY = "disappearing_messages_type"
    const val DOWNLOAD_URL_KEY               = "session_download_url" // Used to invite people to download Session
    const val EMOJI_KEY                      = "emoji"
    const val ETHEREUM_KEY                   = "ethereum"
    const val FILE_TYPE_KEY                  = "file_type"
    const val GROUP_NAME_KEY                 = "group_name"
    const val ICON_KEY                       = "icon"
    const val MEMBERS_KEY                    = "members"
    const val MESSAGE_COUNT_KEY              = "message_count"
    const val MESSAGE_SNIPPET_KEY            = "message_snippet"
    const val NAME_KEY                       = "name"
    const val NETWORK_NAME_KEY               = "network_name"
    const val OTHER_NAME_KEY                 = "other_name"
    const val PRICE_DATA_POWERED_BY_KEY      = "price_data_powered_by"
    const val QUERY_KEY                      = "query"
    const val RELATIVE_TIME_KEY              = "relative_time"
    const val SECONDS_KEY                    = "seconds"
    const val SESSION_DOWNLOAD_URL_KEY       = "session_download_url"
    const val STAKING_REWARD_POOL_KEY        = "staking_reward_pool"
    const val TIME_KEY                       = "time"
    const val TIME_LARGE_KEY                 = "time_large"
    const val TIME_SMALL_KEY                 = "time_small"
    const val TOKEN_BONUS_TITLE_KEY          = "token_bonus_title"
    const val TOKEN_NAME_LONG_KEY            = "token_name_long"
    const val TOKEN_NAME_LONG_PLURAL_KEY     = "token_name_long_plural"
    const val TOKEN_NAME_SHORT_KEY           = "token_name_short"
    const val TOTAL_COUNT_KEY                = "total_count"
    const val URL_KEY                        = "url"
    const val VALUE_KEY                      = "value"
    const val VERSION_KEY                    = "version"
    const val LIMIT_KEY                      = "limit"
}