// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Utils.proto
// Protobuf Java Version: 4.27.1

package org.session.libsignal.protos;

public final class UtilProtos {
  private UtilProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      UtilProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ByteArrayListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ByteArrayList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes content = 1;</code>
     * @return A list containing the content.
     */
    java.util.List<com.google.protobuf.ByteString> getContentList();
    /**
     * <code>repeated bytes content = 1;</code>
     * @return The count of content.
     */
    int getContentCount();
    /**
     * <code>repeated bytes content = 1;</code>
     * @param index The index of the element to return.
     * @return The content at the given index.
     */
    com.google.protobuf.ByteString getContent(int index);
  }
  /**
   * Protobuf type {@code signalservice.ByteArrayList}
   */
  public static final class ByteArrayList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:signalservice.ByteArrayList)
      ByteArrayListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        ByteArrayList.class.getName());
    }
    // Use ByteArrayList.newBuilder() to construct.
    private ByteArrayList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ByteArrayList() {
      content_ = emptyList(com.google.protobuf.ByteString.class);
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.session.libsignal.protos.UtilProtos.internal_static_signalservice_ByteArrayList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.session.libsignal.protos.UtilProtos.internal_static_signalservice_ByteArrayList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.session.libsignal.protos.UtilProtos.ByteArrayList.class, org.session.libsignal.protos.UtilProtos.ByteArrayList.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> content_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <code>repeated bytes content = 1;</code>
     * @return A list containing the content.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getContentList() {
      return content_;
    }
    /**
     * <code>repeated bytes content = 1;</code>
     * @return The count of content.
     */
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated bytes content = 1;</code>
     * @param index The index of the element to return.
     * @return The content at the given index.
     */
    public com.google.protobuf.ByteString getContent(int index) {
      return content_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < content_.size(); i++) {
        output.writeBytes(1, content_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < content_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(content_.get(i));
        }
        size += dataSize;
        size += 1 * getContentList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.session.libsignal.protos.UtilProtos.ByteArrayList)) {
        return super.equals(obj);
      }
      org.session.libsignal.protos.UtilProtos.ByteArrayList other = (org.session.libsignal.protos.UtilProtos.ByteArrayList) obj;

      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.session.libsignal.protos.UtilProtos.ByteArrayList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.session.libsignal.protos.UtilProtos.ByteArrayList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ByteArrayList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ByteArrayList)
        org.session.libsignal.protos.UtilProtos.ByteArrayListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.session.libsignal.protos.UtilProtos.internal_static_signalservice_ByteArrayList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.session.libsignal.protos.UtilProtos.internal_static_signalservice_ByteArrayList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.session.libsignal.protos.UtilProtos.ByteArrayList.class, org.session.libsignal.protos.UtilProtos.ByteArrayList.Builder.class);
      }

      // Construct using org.session.libsignal.protos.UtilProtos.ByteArrayList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        content_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.session.libsignal.protos.UtilProtos.internal_static_signalservice_ByteArrayList_descriptor;
      }

      @java.lang.Override
      public org.session.libsignal.protos.UtilProtos.ByteArrayList getDefaultInstanceForType() {
        return org.session.libsignal.protos.UtilProtos.ByteArrayList.getDefaultInstance();
      }

      @java.lang.Override
      public org.session.libsignal.protos.UtilProtos.ByteArrayList build() {
        org.session.libsignal.protos.UtilProtos.ByteArrayList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.session.libsignal.protos.UtilProtos.ByteArrayList buildPartial() {
        org.session.libsignal.protos.UtilProtos.ByteArrayList result = new org.session.libsignal.protos.UtilProtos.ByteArrayList(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.session.libsignal.protos.UtilProtos.ByteArrayList result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          content_.makeImmutable();
          result.content_ = content_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.session.libsignal.protos.UtilProtos.ByteArrayList) {
          return mergeFrom((org.session.libsignal.protos.UtilProtos.ByteArrayList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.session.libsignal.protos.UtilProtos.ByteArrayList other) {
        if (other == org.session.libsignal.protos.UtilProtos.ByteArrayList.getDefaultInstance()) return this;
        if (!other.content_.isEmpty()) {
          if (content_.isEmpty()) {
            content_ = other.content_;
            content_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureContentIsMutable();
            content_.addAll(other.content_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureContentIsMutable();
                content_.add(v);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> content_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureContentIsMutable() {
        if (!content_.isModifiable()) {
          content_ = makeMutableCopy(content_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @return A list containing the content.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getContentList() {
        content_.makeImmutable();
        return content_;
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @return The count of content.
       */
      public int getContentCount() {
        return content_.size();
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @param index The index of the element to return.
       * @return The content at the given index.
       */
      public com.google.protobuf.ByteString getContent(int index) {
        return content_.get(index);
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @param index The index to set the value at.
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureContentIsMutable();
        content_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @param value The content to add.
       * @return This builder for chaining.
       */
      public Builder addContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureContentIsMutable();
        content_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @param values The content to add.
       * @return This builder for chaining.
       */
      public Builder addAllContent(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureContentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, content_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signalservice.ByteArrayList)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ByteArrayList)
    private static final org.session.libsignal.protos.UtilProtos.ByteArrayList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.session.libsignal.protos.UtilProtos.ByteArrayList();
    }

    public static org.session.libsignal.protos.UtilProtos.ByteArrayList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ByteArrayList>
        PARSER = new com.google.protobuf.AbstractParser<ByteArrayList>() {
      @java.lang.Override
      public ByteArrayList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ByteArrayList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ByteArrayList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.session.libsignal.protos.UtilProtos.ByteArrayList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ByteArrayList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signalservice_ByteArrayList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Utils.proto\022\rsignalservice\" \n\rByteArra" +
      "yList\022\017\n\007content\030\001 \003(\014B*\n\034org.session.li" +
      "bsignal.protosB\nUtilProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_signalservice_ByteArrayList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signalservice_ByteArrayList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_signalservice_ByteArrayList_descriptor,
        new java.lang.String[] { "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
